### ISSUE TITLE
Optimisation de code

### ISSUE THREAD

**Issue by kizza2** [NeyRox-B4D-DEV/Webhooks-Spammer#1]
Hey, à l'époque j'avais regardé ta vidéo YouTube pour ce webhook spammer et j'avais bien aimé le concept, maintenant j'ai appris à développé en python et je me suis rappelé de toi, donc j'ai re regardé ton code et je te propose cette alternative pour l'optimisé:

from dhooks import Webhook, File, Embed
import requests
import pyautogui, time
import sys
import os
import pyfiglet
from colorama import init
from termcolor import cprint
from pyfiglet import figlet_format
from os import system

system("title " + "WEBHOOK SPAMMER")

os.system("cls")

text1="Webhook spammer By NeyRox"
cprint(figlet_format(text1, font="Basic"), "green") 

embed = Embed(
    description='STOP SENDING LOGGERS SKID :sunglasses:',
    color=0x5CDBF0,
    foistamp='now'
)

web = input("\u001b[31mEntre l'URL du webhook: ")

os.system("cls")

hook = Webhook(web)

image1 = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZkfQK3F_ge3ZbcZPe6B-3aO6hocaQEdilcQ&usqp=CAU'
image2 = 'https://i.imgur.com/xpqgA9z.jpg'
image3 = 'https://pbs.twimg.com/media/Bpvdm-QIgAAsoX5.jpg'

embed.set_author(name='CLOWN', icon_url=image2)
embed.add_field(name='YOURE A FUCKING CLOWN', value='HAHAHAHA')
embed.set_footer(text='FUCK YOU', icon_url=image3)

embed.set_thumbnail(image2)
embed.set_image(image1)

text2="SPAM STARTED"
cprint(figlet_format(text2, font="Basic"), "red")
boucle = 0
nbre_de_spam = 30
while boucle < nbre_de_spam:
    hook.send(embed=embed)
    boucle += 1
    if boucle % 5 == 0:
        print("Vous avez spammé", boucle, "fois!")
print("\u001b[31mSpammer 30 fois, relance le logiciel pour spam!")
time.sleep(10)

Bonne journée / soirée à toi !

**Comment by NeyRoxWZ** [comment]
Merci de ton partage, je m’en occuperai. Merci de t’être souvenu de moi ;). Bonne journée.
